version: 2.1

workflows:
  playtime:
    jobs:
      - build

aliases:
  - &buildImage cimg/node:14.16.0-browsers

jobs:
  build:
    docker:
      - image: *buildImage
    steps:
      - run:
          command: |
            while true; do
              sleep 2
              ps auxwwf
              echo "=================="
            done
          background: true
      - run: sleep 20
  