version: 2.1

workflows:
  playtime:
    jobs:
      - build:
          context: tests

aliases:
  - &buildImage cimg/node:14.16.0-browsers

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - run:
          name: sample name
          command: echo -n he; echo llo there
      - run:
          name: print env
          command: env
      - run:
          name: print processes
          command: ps -ef
      - run:
          name: Create some test results
          command: |
            while true; do
              sleep 2
              ps auxwwf
              echo "=================="
            done
          background: true
      - run: sleep 10
      - run: sleep 10
      - run: sleep 10
      - run: sleep 10
      - run: sleep 200
  