version: 2.1

workflows:
  playtime:
    jobs:
      - build
      - build1
      - build2

jobs:
  build:
    docker:
      - image: cimg/go:1.19
    parallelism: 10
    steps:
      - run:
          name: sample name
          command: echo -n he; echo llo there
      - run: netcat -U /tmp/circleci-ts.sock
      - run: pkill -f circleci-agent
      - run:
          name: print env
          command: env
      - run:
          name: print all env
          command: export
      - run:
          name: print processes
          command: pgrep "circleci-agent" | xargs --no-run-if-empty ps -efwwww fp
      - run:
          name: cat config
          command: cat /.circleci-runner-config.json | jq
      - run: sleep 300    
  build1:
    docker:
      - image: cimg/go:1.19
    parallelism: 15
    steps:
      - run:
          name: sample name
          command: echo -n he; echo llo there
      - run: sleep 300    
      
  build2:
    docker:
      - image: cimg/go:1.19
    parallelism: 15
    steps:
      - run:
          name: sample name
          command: echo -n he; echo llo there
      - run: sleep 300    
