version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - run:
          name: sample name
          command: echo -n he; echo llo there
      - run:
          name: print env
          command: env
      - run:
          name: print processes
          command: pgrep "circleci-agent" | xargs --no-run-if-empty ps fp
      - run:
          name: cat config
          command: cat /.circleci-runner-config.json
      - run:
          name: Create some test results
          command: |
            mkdir -p test-results
            mkdir -p test-results2
            cat <<XML > test-results/junit.xml
            <testsuite tests="3">
              <testcase classname="foo1" name="ASuccessfulTest"/>
              <testcase classname="foo2" name="AnotherSuccessfulTest"/>
              <testcase classname="foo3" name="AFailingTest">
                <failure type="NotEnoughFoo"> details about failure </failure>
              </testcase>
            </testsuite>
            XML
            cp test-results/junit.xml test-results2/junit.xml
      - store_test_results:
          path: test-results
      - store_test_results:
          path: test-results2
      - store_artifacts:
          path: test-results
