version: 2.1

workflows:
  playtime:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/go:1.19
    parallelism: 50
    steps:
      - run:
          name: sample name
          command: echo -n he; echo llo there
      - run: netcat -U /tmp/circleci-ts.sock
      - run: sleep 600
      - run:
          name: print env
          command: env
      - run:
          name: print all env
          command: export
      - run:
          name: print processes
          command: pgrep "circleci-agent" | xargs --no-run-if-empty ps -efwwww fp
      - run:
          name: cat config
          command: cat /.circleci-runner-config.json | jq
      - checkout
      - run:
          name: dump
          command: go run ./dump

